#!/usr/bin/perl -w

use warnings;
use strict;
use POSIX;
use Getopt::Long;
use File::Path;
use File::Basename;
use Pod::Usage;

=head1 NAME

clean_illumina_platinum

=head1 SYNOPSIS

 clean_clean_illumina_platinum [options]  
  
=head1 DESCRIPTION
 
 Removes unnecessary annotation.  
 
=cut

#option variables
my $help;
my $verbose;
my $debug;

#initialize options
Getopt::Long::Configure ('bundling');

if(!GetOptions ('h'=>\$help, 'v'=>\$verbose, 'd'=>\$debug) 
  || scalar(@ARGV)!=1)
{
    if ($help)
    {
        pod2usage(-verbose => 2);
    }
    else
    {
        pod2usage(1);
    }
}

my $vcfFile = $ARGV[0];

open(VCF, "zcat $vcfFile |") || die "Cannot open $vcfFile";

while(<VCF>)
{
    chomp;
    
    if (/^#/)
    {
        if (/^##fileformat=VCFv4.1/)
        {
            print "##fileformat=VCFv4.1\n";
            printb37Contigs();            
        }
        elsif (/^##contig/)
        {
            #ignore old contigs
        }
        elsif (/^##INFO=<ID=callers/)
        {
            $_ =~ /(##[^#]+>)(##[^#]+>)/;
            print "$1\n";
            print "$2\n";
        }
        elsif (/^##reference/)
        {
            print "##reference=grch37\n";
        }
        elsif (/^##FORMAT=<ID=ED/)
        {
            print "##FORMAT=<ID=ED,Number=1,Type=Integer,Description=\"Per-sample edit distance\">\n";
        }
        else
        {
            print "$_\n";
        }  
    }
    else
    {
        my ($chrom, $pos, $id, $ref, $alt, $qual, $filter, $info, $format, $genotypes) = split("\t", $_, 10);
        
        $chrom =~ s/^chr//;
        
        #print "$chrom\t$pos\t.\t$ref\t$alt\t.\t$filter\t$info\t$format\t$genotypes\n";
        print "$chrom\t$pos\t$id\t$ref\t$alt\t$qual\t$filter\t$info\t$format\t$genotypes\n";
    
    }
}

close(VCF);

sub printb37Contigs
{
    print "##contig=<ID=1,length=249250621,assembly=b37>\n";
    print "##contig=<ID=2,length=243199373,assembly=b37>\n";
    print "##contig=<ID=3,length=198022430,assembly=b37>\n";
    print "##contig=<ID=4,length=191154276,assembly=b37>\n";
    print "##contig=<ID=5,length=180915260,assembly=b37>\n";
    print "##contig=<ID=6,length=171115067,assembly=b37>\n";
    print "##contig=<ID=7,length=159138663,assembly=b37>\n";
    print "##contig=<ID=8,length=146364022,assembly=b37>\n";
    print "##contig=<ID=9,length=141213431,assembly=b37>\n";
    print "##contig=<ID=10,length=135534747,assembly=b37>\n";
    print "##contig=<ID=11,length=135006516,assembly=b37>\n";
    print "##contig=<ID=12,length=133851895,assembly=b37>\n";
    print "##contig=<ID=13,length=115169878,assembly=b37>\n";
    print "##contig=<ID=14,length=107349540,assembly=b37>\n";
    print "##contig=<ID=15,length=102531392,assembly=b37>\n";
    print "##contig=<ID=16,length=90354753,assembly=b37>\n";
    print "##contig=<ID=17,length=81195210,assembly=b37>\n";
    print "##contig=<ID=18,length=78077248,assembly=b37>\n";
    print "##contig=<ID=19,length=59128983,assembly=b37>\n";
    print "##contig=<ID=20,length=63025520,assembly=b37>\n";
    print "##contig=<ID=21,length=48129895,assembly=b37>\n";
    print "##contig=<ID=22,length=51304566,assembly=b37>\n";
#    print "##contig=<ID=X,length=155270560,assembly=b37>\n";
#    print "##contig=<ID=Y,length=59373566,assembly=b37>\n";
#    print "##contig=<ID=MT,length=16569,assembly=b37>\n";
#    print "##contig=<ID=GL000207.1,length=4262,assembly=b37>\n";
#    print "##contig=<ID=GL000226.1,length=15008,assembly=b37>\n";
#    print "##contig=<ID=GL000229.1,length=19913,assembly=b37>\n";
#    print "##contig=<ID=GL000231.1,length=27386,assembly=b37>\n";
#    print "##contig=<ID=GL000210.1,length=27682,assembly=b37>\n";
#    print "##contig=<ID=GL000239.1,length=33824,assembly=b37>\n";
#    print "##contig=<ID=GL000235.1,length=34474,assembly=b37>\n";
#    print "##contig=<ID=GL000201.1,length=36148,assembly=b37>\n";
#    print "##contig=<ID=GL000247.1,length=36422,assembly=b37>\n";
#    print "##contig=<ID=GL000245.1,length=36651,assembly=b37>\n";
#    print "##contig=<ID=GL000197.1,length=37175,assembly=b37>\n";
#    print "##contig=<ID=GL000203.1,length=37498,assembly=b37>\n";
#    print "##contig=<ID=GL000246.1,length=38154,assembly=b37>\n";
#    print "##contig=<ID=GL000249.1,length=38502,assembly=b37>\n";
#    print "##contig=<ID=GL000196.1,length=38914,assembly=b37>\n";
#    print "##contig=<ID=GL000248.1,length=39786,assembly=b37>\n";
#    print "##contig=<ID=GL000244.1,length=39929,assembly=b37>\n";
#    print "##contig=<ID=GL000238.1,length=39939,assembly=b37>\n";
#    print "##contig=<ID=GL000202.1,length=40103,assembly=b37>\n";
#    print "##contig=<ID=GL000234.1,length=40531,assembly=b37>\n";
#    print "##contig=<ID=GL000232.1,length=40652,assembly=b37>\n";
#    print "##contig=<ID=GL000206.1,length=41001,assembly=b37>\n";
#    print "##contig=<ID=GL000240.1,length=41933,assembly=b37>\n";
#    print "##contig=<ID=GL000236.1,length=41934,assembly=b37>\n";
#    print "##contig=<ID=GL000241.1,length=42152,assembly=b37>\n";
#    print "##contig=<ID=GL000243.1,length=43341,assembly=b37>\n";
#    print "##contig=<ID=GL000242.1,length=43523,assembly=b37>\n";
#    print "##contig=<ID=GL000230.1,length=43691,assembly=b37>\n";
#    print "##contig=<ID=GL000237.1,length=45867,assembly=b37>\n";
#    print "##contig=<ID=GL000233.1,length=45941,assembly=b37>\n";
#    print "##contig=<ID=GL000204.1,length=81310,assembly=b37>\n";
#    print "##contig=<ID=GL000198.1,length=90085,assembly=b37>\n";
#    print "##contig=<ID=GL000208.1,length=92689,assembly=b37>\n";
#    print "##contig=<ID=GL000191.1,length=106433,assembly=b37>\n";
#    print "##contig=<ID=GL000227.1,length=128374,assembly=b37>\n";
#    print "##contig=<ID=GL000228.1,length=129120,assembly=b37>\n";
#    print "##contig=<ID=GL000214.1,length=137718,assembly=b37>\n";
#    print "##contig=<ID=GL000221.1,length=155397,assembly=b37>\n";
#    print "##contig=<ID=GL000209.1,length=159169,assembly=b37>\n";
#    print "##contig=<ID=GL000218.1,length=161147,assembly=b37>\n";
#    print "##contig=<ID=GL000220.1,length=161802,assembly=b37>\n";
#    print "##contig=<ID=GL000213.1,length=164239,assembly=b37>\n";
#    print "##contig=<ID=GL000211.1,length=166566,assembly=b37>\n";
#    print "##contig=<ID=GL000199.1,length=169874,assembly=b37>\n";
#    print "##contig=<ID=GL000217.1,length=172149,assembly=b37>\n";
#    print "##contig=<ID=GL000216.1,length=172294,assembly=b37>\n";
#    print "##contig=<ID=GL000215.1,length=172545,assembly=b37>\n";
#    print "##contig=<ID=GL000205.1,length=174588,assembly=b37>\n";
#    print "##contig=<ID=GL000219.1,length=179198,assembly=b37>\n";
#    print "##contig=<ID=GL000224.1,length=179693,assembly=b37>\n";
#    print "##contig=<ID=GL000223.1,length=180455,assembly=b37>\n";
#    print "##contig=<ID=GL000195.1,length=182896,assembly=b37>\n";
#    print "##contig=<ID=GL000212.1,length=186858,assembly=b37>\n";
#    print "##contig=<ID=GL000222.1,length=186861,assembly=b37>\n";
#    print "##contig=<ID=GL000200.1,length=187035,assembly=b37>\n";
#    print "##contig=<ID=GL000193.1,length=189789,assembly=b37>\n";
#    print "##contig=<ID=GL000194.1,length=191469,assembly=b37>\n";
#    print "##contig=<ID=GL000225.1,length=211173,assembly=b37>\n";
#    print "##contig=<ID=GL000192.1,length=547496,assembly=b37>\n";
}
