#!/usr/bin/perl

use warnings;
use strict;
use POSIX qw(ceil floor);
use File::Basename;
use File::Path;
use Getopt::Long;
use Pod::Usage;

=head1 NAME

create_grch37_pseudoautosomal_region_bed

=head1 SYNOPSIS

create_grch37_pseudoautosomal_region_bed [options] <filename>

    -v  verbose
    -d  debug
    -o  output contig directory.

    usage: convert_vcf_2_bed input.vcf

    Creates a BED file containing the pseudoautosomal regions for GRCh37.

=head1 DESCRIPTION

=cut

#option variables
my $help;
my $outputBEDFile;

#initialize options
Getopt::Long::Configure ('bundling');

if(!GetOptions ('h'=>\$help,
                'o:s'=>\$outputBEDFile)
    || scalar(@ARGV)!=0)
{
    if ($help)
    {
        pod2usage(-verbose => 2);
    }
    else
    {
        pod2usage(1);
    }
}

if ($outputBEDFile =~ /bed.gz$/)
{
    open(OUT, "| bgzip -c > $outputBEDFile");
}
else
{
    open(OUT, ">$outputBEDFile");
}

#GRCh37 pseudoautosomal regions
#PAR1	X	60,001	    2,699,520
#       Y	10,001	    2,649,520
#PAR2	X	154,931,044	155,260,560
#       Y	59,034,050	59,363,566

#note that positions are 0 based exclusive
print OUT "X\t60000\t2699520\n";
print OUT "X\t154931043\t155260560\n";
print OUT "Y\t10000\t2649520\n";
print OUT "Y\t59034049\t59363566\n";

close(OUT);
